# Generated by Django 4.2.4 on 2023-08-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
